apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracking-ui
  template:
    metadata:
      labels:
        app: expense-tracking-ui
    spec:
      containers:
      - name: expense-tracking-ui
        image: ghcr.io/tiagogauziski/expense-tracking-ui:master
        imagePullPolicy: Always
        volumeMounts:
          - name: config-volume
            mountPath: /usr/share/nginx/html/assets/config.json
            subPath: config.json
        ports:
          - name: http
            containerPort: 80
      volumes:
      - name: config-volume
        configMap:
          name: ui-config
          items:
          - key: config.json
            path: config.json
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  labels:
    app: expense-tracking-ui
spec:
  selector:
    app: expense-tracking-ui
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: http
  type: LoadBalancer