apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: expense-tracking-api
  template:
    metadata:
      labels:
        app: expense-tracking-api
    spec:
      containers:
      - name: expense-tracking-api
        image: ghcr.io/tiagogauziski/expense-tracking-api:master
        imagePullPolicy: Always
        env:
        - name: ConnectionStrings__ExpensesDatabase
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: connectionString
        # readinessProbe:
        #   httpGet:
        #     path: /healthz/ready
        #     port: 80
        #   initialDelaySeconds: 10
        #   timeoutSeconds: 2
        # livenessProbe:
        #   httpGet:
        #     path: /healthz/live
        #     port: 80
        #   initialDelaySeconds: 10
        #   timeoutSeconds: 2
        ports:
          - name: http
            containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
  type: LoadBalancer